#!/usr/bin/env bash
# tranfer files from clinet to server

if [ "$#" -ne 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

PATH_TO_FILE=$1
SERVER_IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4

# Transfer the file using scp with strict host key checking disabled
scp -i "$PATH_TO_SSH_KEY" -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME@$SERVER_IP:~/"

# Check if the scp command was successful
if [ "$?" -eq 0 ]; then
  echo "File transferred successfully to $USERNAME@$SERVER_IP:~/"
else
  echo "Failed to transfer the file."
  exit 1
fi
