#!/usr/bin/env bash
#this displays best school 10 times with a condition
i=0
while ((i != 11)); do
    echo "Best School"
    if ((i == 9)); then
	echo "Best School"
        echo "hi"
    fi
    ((i++))
done
