#!/usr/bin/env bash
#this displays best school 10 times with a condition
i=
i=00
while ((i < 10)); do
    if ((i == 8)); then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    ((i++))
done
