#!/usr/bin/env bash
#this script loops from 1 to 10 with conditions
i=0
while((i<10));do
     if((i==3));then
         echo 'bad luck'
     elif((i==7));then
	echo 'good luck'
     else 
     echo 'Best School'
     fi
	((i++))
done	 		
