#!/usr/bin/env bash
#this script loops from 1 to 20 with conditions
i=1
while ((i <= 20)); do
    case $i in
        4)
            echo "4"
            echo "bad luck from China"
            ;;
        9)
            echo "9"
            echo "bad luck from Japan"
            ;;
        17)
            echo "17"
            echo "bad luck from Italy"
            ;;
        *)
            echo "$i"
            ;;
    esac
    ((i++))
done
