#!/usr/bin/env bash
#this script loops from 1 to 20 with conditions
i=1
while((i!=21));do
     if((i==4));then
	 echo "$i"    
         echo 'bad luck from China'
     elif((i==9));then
	echo "$i"
	echo 'good luck form Japan'
     elif((i==17));then
      echo "$i"
	echo "bad luck from Italy"      
     else 
     echo "$i"
     fi
	((i++))
done	 		
