#!/usr/bin/env bash
#this script displays the clock from 0 to 12 and from 0 to 59
i=0;
while((i!=13));do
j=1
echo "Hour: $i"
 while((j!=60 && i!=12));do
    echo "$j"
    ((j++))
   done
 ((i++))
done
