#!/usr/bin/env bash
#this script displays the clock from 0 to 12 and from 0 to 59
i=0
j=1
while [ $i -ne 13 ]; do
     echo "Hour: $i"
     i=$((i+1))
     while [ $j -ne 60 ]; do
     	   echo $j
	   j=$((j+1))
     done
     j=1
done
