#!/usr/bin/env bash
#this script displays the clock from 0 to 12 and from 0 to 59
i=1;
echo "Hour: 0"
while((i!=13));do
j=1
 while((j!=60));do
    echo "$j"
    ((j++))
   done
   echo "Hour: $i"
 ((i++))
done
