#!/usr/bin/env bash 
#this is a comment
for file in *; do
    # Check if the file is not hidden and contains a dash
    if [[ ! "$file" == .* && "$file" =~ - ]]; then
        # Extract the part of the name after the first dash
        name=$(echo "$file" | cut -d '-' -f 2-)
        echo "$name"
    fi
done
